# detect github repo changes
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: foo
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./demo1/foo
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-demo
  targetNamespace: foo
  timeout: 3m0s
  wait: true
