---
# demo1/loki-release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: o11y
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: grafana
      version: ">=8.0.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    remediation:
      retries: 3
  targetNamespace: o11y
  values:
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            url: http://http://prometheus-server.o11y.svc.cluster.local/
            isDefault: true
          - name: Loki
            type: loki
            url: http://o11y-loki-gateway.o11y.svc.cluster.local/
