# demo1/loki-release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: o11y
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: grafana
      version: ">=4.0.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    remediation:
      retries: 3
  targetNamespace: o11y
  values:
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          url: http://loki-gateway.monitoring.svc.cluster.local/
          isDefault: true
