---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - loki.yaml
  - grafana.yaml
  - prometheus.yaml
configMapGenerator:
  - name: grafana-dashboards
    files:
      - grafana-dashboards/k8s-addons-prometheus.json
      - grafana-dashboards/k8s-addons-trivy-operator.json
      - grafana-dashboards/k8s-system-api-server.json
      - grafana-dashboards/k8s-system-coredns.json
      - grafana-dashboards/k8s-views-global.json
      - grafana-dashboards/k8s-views-namespaces.json
      - grafana-dashboards/k8s-views-nodes.json
      - grafana-dashboards/k8s-views-pods.json
    options:
      labels:
        grafana_dashboard: "true"
