---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: o11y
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: ">=45.0.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    grafana:
      enabled: false
    kube-state-metrics:
      customResourceState:
        config:
          spec:
            resources:
              - groupVersionKind:
                  group: helm.toolkit.fluxcd.io
                  version: "v2"
                  kind: HelmRelease
                metricNamePrefix: gotk
                metrics:
                  - name: "resource_info"
                    help: "The current state of a GitOps Toolkit resource."
                    each:
                      type: Info
                      info:
                        labelsFromPath:
                          name: [metadata, name]
                          exported_namespace: [metadata, namespace]
                          suspended: [spec, suspend]
                          ready: [status, conditions, "[type=Ready]", status]
    prometheus:
      prometheusSpec:
        podMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        additionalScrapeConfigs:
          - job_name: 'flux'
            kubernetes_sd_configs:
              - role: pod
                namespaces:
                  names:
                    - flux-system
            relabel_configs:
              - source_labels: [__meta_kubernetes_pod_label_app]
                regex: (source-controller|kustomize-controller|helm-controller)
                action: keep
              - source_labels: [__meta_kubernetes_pod_container_port_number]
                regex: "8080"
                action: keep
