apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: o11y
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: prometheus
      version: ">=15.0.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    remediation:
      retries: 3
  values:
